name: MinigameWorldScript
main: io.github.rypofalem.minigameworldscript.MinigameWorldScriptPlugin
version: 1.0
website: rypofalem.github.io
author: RypoFalem
description: Runs some commands to make a minigame world.
depend: [Multiverse-Core, zPermissions, PlayerCache]
commands:
  mgws:
    description: Creates a new minigames-ready world
    usage: §c /mgws <playername> <worldname> <minigame> [environment]
    permission: mgws.use
permissions:
  mgws.use:
    description: Can use the script
    default: op